# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'USC Films' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for USC Films
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 6.0'
  pod "youtube-ios-player-helper", "~> 1.0.3"
end
